build_platform:
  osx_arm64: osx_64
  linux_ppc64le: linux_64
  linux_aarch64: linux_64
channel_priority: strict
conda_forge_output_validation: true
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
provider:
  linux_ppc64le: default
  linux_aarch64: default
